### PR TITLE
Related to issue #9, added callback to format the display value, in custom formats, including string.

### PR DESCRIPTION
**Pull request by fernandocode**
Added attribute "valueFormat" in `ngx-gauge`, to be able to treat/format the value to be displayed in the Gauge.

Added **example** project, to present and test functionality.

Related to issue #9

### CODE REVIEW

**Comment by fernandocode** [comment]
As I needed this functionality I did a new publication in npm to use, once this functionality is incorporated the official version I will unpublish my package from npm.

[If anyone wants this temporary version:](https://www.npmjs.com/package/ngxcode-gauge)

`npm install ngxcode-gauge`

**Comment by fernandocode** [comment]
Close, will be implemented as defined in #9 in discussion on the topic.

**Comment by fernandocode** [comment]
Custom Display was implemented: labels, value, append, prepend.

But I came across a layout problem that I do not know how to proceed, as I had to create treatment for the ng-content, to continue working on compatibility with the old versions, I had to put them in some spans with no style, the HTML code is legible and understandable, it has been indented, but this ends up causing an extra space between the value and append.

Note this example in the [old version of the library](https://stackblitz.com/edit/angular-vclt9x?file=app%2Fapp.component.html), and in [my version](https://stackblitz.com/edit/angular-xbw58d?file=app%2Fapp.component.html). (note between "28.3" and "km", a much larger space in my version).

I have three options:
- [Treat this inline; (it is difficult to understand the HTML code)](https://stackblitz.com/edit/angular-ctevcj?file=app%2Fapp.component.html);
- [Leave it like this and try to deal with css (I already tried with margin negative, and it works, but in the case of example 3, where the source of the value is customized it ends up being completely wrong).](https://stackblitz.com/edit/angular-nyombm?file=app%2Fapp.component.html)
- Or just leave it like that. =/

I prefer the first option, but I accept suggestions (@ashish-chopra  and @SpartanNico94).

This change is committed on [my fork](https://github.com/fernandocode/ngx-gauge) too

**Comment by ashish-chopra** [comment]
Great Job @fernandocode 

I saw your examples, they are awesome. Just few comments on the code conventions I am following:

1. Put all your directives in a single file `gauge-directives.ts` 
2. In `gauge.html` your code is creating extra empty `<span>` nodes when there is no `<ngx-gauge-prepend>` provided by user. So use following code which I was writing:

```html

<div class="reading-block" #reading [style.fontSize]="size * 0.22 + 'px'" [style.lineHeight]="size + 'px'">
    <u class="reading-affix" [ngSwitch]="_prependChild != null">
        <ng-content select="ngx-gauge-prepend" *ngSwitchCase="true"></ng-content>
        <ng-container *ngSwitchCase="false">{{prepend}}</ng-container>
    </u>
    <ng-container [ngSwitch]="_valueDisplayChild != null">
        <ng-content *ngSwitchCase="true" select="ngx-gauge-value"></ng-content>
        <ng-container *ngSwitchCase="false">{{value | number}}</ng-container>
    </ng-container>
    <u class="reading-affix" [ngSwitch]="_appendChild != null">
        <ng-content select="ngx-gauge-append" *ngSwitchCase="true"></ng-content>
        <ng-container *ngSwitchCase="false">{{append}}</ng-container>
    </u>
</div>
<div class="reading-label" 
     [style.fontSize]="size / 13 + 'px'" 
     [style.lineHeight]="(5 * size / 13) + size + 'px'"
     [ngSwitch]="_labelChild != null">
     <ng-content select="ngx-gauge-label" *ngSwitchCase="true"></ng-content>
     <ng-container *ngSwitchCase="false">{{label}}</ng-container>
</div>
<canvas #canvas [width]="size" [height]="size"></canvas>
```

and in `gauge.ts` add following code in your class:
```js
    @ContentChild(NgxGaugeLabel) _labelChild: NgxGaugeLabel;
    @ContentChild(NgxGaugePrepend) _prependChild: NgxGaugePrepend;
    @ContentChild(NgxGaugeAppend) _appendChild: NgxGaugeAppend;
    @ContentChild(NgxGaugeValue) _valueDisplayChild: NgxGaugeValue;
```

This code atleast maintain the same DOM structure without introducing anything extra. However when it is written well indented like this, then I observed extra spacing, see the screenshot below. Space between append, value, prepend:

gauge-screenshot

By preparing this, you can submit a PR, I will merge it into a feature branch and then look into CSS from scratch. See if you can decipher the CSS issue. I think it is due to line-height and white-space nowrap thing.

**Comment by ashish-chopra** [comment]
I created a branch `feature/gauge-directives`, use that to send a pull request. I will close this issue here and will create a fresh issue on CSS and will take up the discussion there if you are interested.

**Comment by fernandocode** [comment]
> However when it is written well indented like this, then I observed extra spacing, see the screenshot below. Space between append, value, prepend:
@ashish-chopra 

This is because of the line breaks in the template, everything between append, value and prepend should be on the same line, it was already my problem of the other code, it was not the extra nodes, at least not with that.

If you want to better understand what is happening there, follow [this question in the sopt (It's in Portuguese](https://pt.stackoverflow.com/q/276760/2998)). I am explaining what is happening to try to understand the problem better and think about a possible way to avoid it.

**Comment by fernandocode** [comment]
@ashish-chopra about the spacing the code would have to be [this way](https://stackblitz.com/edit/angular-bwrcdk?file=libs%2Fngx-gauge%2Fsrc%2Fgauge%2Fgauge.html) so that the spacing does not occur, but it gets really confusing, and anyone who is giving maintenance would indent it. :(

**Comment by fernandocode** [comment]
@ashish-chopra, the best way I got it was like this: https://stackblitz.com/edit/angular-uaapjs?file=libs/ngx-gauge/src/gauge/gauge.html

What do you think? Any suggestion?

**Comment by ashish-chopra** [comment]
Thanks for your detailed work. Your pull request #12 seems perfect. I will take it.

**Pull request closed without merging**
