### PR TITLE
fix usage w/ negative numbers

### LINKED ISSUE #134: I got an issue when I entered some negative value in markers
For some reason it understand the 0 is the low limit of the value and not an negative value that's  the reason for cause the bug...

Screenshot_1
Screenshot_2

### PR DESCRIPTION
**Pull request by johnm747**
- Add offset and extra safeguards when using negative numbers
- Modified code to follow linting rules in some areas
- Fixes #134

### CODE REVIEW

**Comment by ashish-chopra** [comment]
I have received your pull request. Thanks for updating some of legacy code. I will merge it by the end of this week, right now travelling.

**Comment by johnm747** [comment]
Hello, I've been meaning to ping on this. Is this pull request still to be merged in?

**Comment by cre8iveroom** [comment]
I wanted to check on the status of this issue. We are wanting to use this gauge and we are also running into issues using negative numbers for all of the markers as well as thresholds. 

The metric we are trying to show, RSSI, deals mostly in negative numbers.

**Comment by johnm747** [comment]
Rebased off master and added some updates. Squashed additional changes and force pushed since the pull request has not been merged yet.

**Comment by ashish-chopra** [comment]
I will release a new version by this weekend. Sorry for the delay.

**Comment by ashish-chopra** [comment]
Hi All,

The new version is released with the fix in this PR. Download v0.7.1.0 from npm. 

Thanks!
Ashish

**Comment by cre8iveroom** [comment]
We recently upgraded to Angular 16 and tried this out. Thanks for the fix!

**Pull request merged**
