### PR TITLE
feat: added markers/ticks/labels and bg color for ranges

### PR DESCRIPTION
**Pull request by sjdrew**
Thanks for a great widget...

I have added additional input parameters to allow markers/ticks with optional labels, font specifications. As well added margin param (needed if labels involved) and bgOpacity property to the thresholds which if specified uses the threshold color with the applied opacity to form the background color for the range.

See below for results:

WaitWell_Admin

WaitWell_Admin

### CODE REVIEW

**Comment by ashish-chopra** [comment]
Thanks for contributing @stevedrew! This addition looks amazing. I will go through it soon!

**Comment by stanislav-kondriukov** [comment]
@ashish-chopra Hello! Will you merge this branch to master? I really need this functionality for my project.
Thank you in advance.

**Comment by ashish-chopra** [comment]
Yup, it's a long pending. I will try to do it over the weekend. Cheers!

**Comment by stanislav-kondriukov** [comment]
@ashish-chopra, Thank you very match! Cheers!

**Comment by stanislav-kondriukov** [comment]
@ashish-chopra, hello! Any status update here?

**Comment by maidadur** [comment]
@ashish-chopra hi, any updates on this issue?

**Comment by maidadur** [comment]
@ashish-chopra hi, appreciate a lot for merging, can u also update the npm package? thanks!

**Comment by ashish-chopra** [comment]
v5.0.0 has been published. Thank you everyone for contributing and I apologize for the delay.

**Pull request merged**
